# Generated by Django 4.1.1 on 2022-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_bookingslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
